---
- name: Add user deploy
  ansible.builtin.user:
    name: deploy
    comment: Deploy
    uid: 1001

- name: Creates directory on project
  file:
    path: /var/www
    state: directory
    owner: deploy
    recurse : yes
    group: deploy

- name: Git clone project
  ansible.builtin.git:
    repo: '{{ repo }}'
    dest: /var/www/slim
  become: yes
  become_user: deploy