---
- name: download PGP-key nginx
  get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /etc/nginx_signing.key

- name: install PGP-key
  apt_key:
    file: /etc/nginx_signing.key
    state: present

- name: add nginx repo deb
  apt_repository:
    repo: deb https://nginx.org/packages/mainline/debian/ bullseye nginx

- name: add Nginx repo deb-src
  apt_repository:
    repo: deb-src https://nginx.org/packages/mainline/debian/ bullseye nginx

- name: delete nginx-common
  apt:
    name: nginx-common
    state: absent

- name: install of debian 11
  apt:
    name: nginx
    update_cache: yes
    state: latest
  notify: restart nginx

- name: delete file example default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: delete file example default from conf.d
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: copy conf file nginx
  copy:
    src: application.conf
    dest: /etc/nginx/conf.d
    mode: 0755
  notify: restart nginx

- name: copy main conf file nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx
    mode: 0755
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    enabled: yes