---

- name: add key
  shell: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 8C718D3B5072E1F5

- name: add apt repo
  shell: echo 'deb http://repo.mysql.com/apt/debian/ bullseye mysql-8.0' > /etc/apt/sources.list.d/mysql.list

- name: install mysql 8
  apt:
    name: mysql-server
    update_cache: yes
    state: latest

- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest
# запускать только в первый раз
#- name: Set MySQL root Password
#  mysql_user:
#    login_host: 'localhost'
#    login_user: 'root'
#    login_password: ''
#    name: 'root'
#    password: '{{ mysql_root_password }}'
#    state: present

- mysql_user:
    login_user: root
    login_password: '{{ mysql_root_password }}'
    name: '{{ mysql_application_login }}'
    password: '{{ mysql_application_password }}'
    append_privs: true
    priv: '*.*:ALL,GRANT'
    state: present

- name: Create a new database
  community.mysql.mysql_db:
    login_user: root
    login_password: '{{ mysql_root_password }}'
    name: '{{ mysql_application_db }}'
    state: present
